export const PATHS = {
  LOGIN: "/login",
  REGISTER: "/register", 
  FORGOT_PASSWORD: "/forgot-password",
  CONFIRM_PASSWORD: "/confirm-password",
  RESET_PASSWORD: "/reset-password",
  
  HOME: "/",
  ABOUT: "/about",
  ORDER: "/order",
  ORDER_STEP: "/order/:step", 
  ORDER_HISTORY: "/orders",
  QUICK_ORDER: "/quick-order/:orderId",
  PROFILE: "/profile",
  FAVORITES: "/favorites",
  ORDERS: "/orders",
  STAFF_DASHBOARD: "/staff",
  
  STAFF: "/staff",
  STAFF_ORDERS: "/staff/orders",
  STAFF_KITCHEN: "/staff/kitchen",
  STAFF_INGREDIENTS: "/staff/ingredients",
  STAFF_PAYMENTS: "/staff/payments",
  
  ADMIN: "/admin",
  ADMIN_REVENUE: "/admin/revenue",
  ADMIN_MENU: "/admin/menu",
  ADMIN_INGREDIENTS: "/admin/ingredients", 
  ADMIN_USERS: "/admin/users",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_FEEDBACK: "/admin/feedback",
  
  UNAUTHORIZED: "/unauthorized",
  UNAUTHENTICATED: "/unauthenticated",
  ERROR: "/error",
  SUCCESS: "/success",
  NOT_FOUND: "*",
};