export const PATHS = {
  LOGIN: "/login",
  REGISTER: "/register", 
  FORGOT_PASSWORD: "/forgot-password",
  CONFIRM_PASSWORD: "/confirm-password",
  RESET_PASSWORD: "/reset-password",
  OAUTH_CALLBACK: "/oauth2/callback",
  
  HOME: "/",
  MENU: "/menu",
  DISH_DETAIL: "/menu/dish/:id",
  ABOUT: "/about",
  CONTACT: "/contact",
  ORDER: "/order",
  ORDER_STEP: "/order/:step", 
  ORDER_HISTORY: "/orders",
  QUICK_ORDER: "/quick-order/:orderId",
  PROFILE: "/profile",
  FAVORITES: "/favorites",
  ORDERS: "/orders",
  STAFF_DASHBOARD: "/staff",
  
  STAFF: "/staff",
  STAFF_ORDERS: "/staff/orders",
  STAFF_KITCHEN: "/staff/kitchen",
  STAFF_INGREDIENTS: "/staff/ingredients",
  STAFF_PAYMENTS: "/staff/payments",
  
  ADMIN: "/admin",
  ADMIN_REVENUE: "/admin/revenue",
  ADMIN_MENU: "/admin/menu",
  ADMIN_INGREDIENTS: "/admin/ingredients", 
  ADMIN_SOLD_INGREDIENTS: "/admin/sold-ingredients",
  ADMIN_ACCOUNTS: "/admin/accounts",
  ADMIN_CUSTOMERS: "/admin/customers",
  ADMIN_STAFF: "/admin/staff",
  ADMIN_NOTIFICATIONS: "/admin/notifications",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_FEEDBACK: "/admin/feedback",
  ADMIN_DISH_CATEGORIES: "/admin/dish-categories",
  ADMIN_DISH_TEMPLATES: "/admin/dish-templates",
  ADMIN_INGREDIENT_CATEGORIES: "/admin/ingredient-categories",
  
  UNAUTHORIZED: "/unauthorized",
  UNAUTHENTICATED: "/unauthenticated",
  ERROR: "/error",
  SUCCESS: "/success",
  NOT_FOUND: "*",
};